version: '3'
services:
  web:
    build: .
    ports:
     - "80:80"
    depends_on:
      - "mongo"
    links:
      - "mongo:mongodb"
  mongo:
    image: "mongo:latest"
    ports:
     - "27017:27017"
    volumes:
    - ~/data:/data/db